package FutsalPackage;

public enum EquiposEnum {
	BOCA , RIVER, INDEPENDIENTE, RACING, HURACAN, SAN_LORENZO, COLOCOLO, 
	PLATENSE, DEFENSORES, NEWELLS, ALDOSIVI, COLON, BANFIELD, VELEZ, ALLBOYS, DEPORTIVO_GENSHIN,
	ROSARIO_CENTRAL, DEF_DE_BELGRANO, GIMNASIA, CHICAGO, EL_PORVENIR, FERROCARRIL_OESTE, URQUIZA, ESTUDIANTES,
	ATLETICO_DE_TUCUMAN, HAT_GUY
}
